on:
  workflow_dispatch
  
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to list top modified functions
    steps:
      - uses: actions/checkout@v4
      - name: get modified functions
        uses: snadi/TopModifiedFunctions@0.1.0-alpha
        with:
          topn: 5
