name: List top modified functions

on:
  workflow_dispatch
  
jobs:
  top-modified-fns:
    runs-on: ubuntu-latest
    name: List top modified functions
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: get modified functions
        uses: snadi/TopModifiedFunctions@v1.1
        with:
          topn: 5
